spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/moneygement
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: create-drop

# p6spy
datasource:
  p6spy:
    enable-logging:
      true
